### ISSUE TITLE
Lowercase letters in Mac address cause syntax error

### ISSUE THREAD

**Issue by a2retro** [burniouf/A2osX#39] opened 2018-07-15 17:37 UTC
Lowercase letters in Mac address cause syntax error in driver load. If you run it a second time with the MAC address in upper case it says hardware not found. Driver can only be loaded once.

**Comment by burniouf** [comment] 2018-07-15 20:52
not really a bug, let's explain behaviour.
- driver detects H/W
- driver try to parse DRV parameters.....failed because of lowercase in MAC, so DRV failback to default MAC
- driver loaded succesfully, and mark the slot as "busy"
- second attempt try do detect H/W again, but skipping the marked "busy" slot
- so H/W not found.

0.9.2 improved the sscanf function to handle lc/UC parsing in HEX string....

**Comment by burniouf** [comment] 2018-09-06 08:11
new MAC address syntax in 0.92:

expected format is  00:aa:34:AA:ED:fE (upper or lowercase)

please check, then close this issue.

**Comment by patrickbst** [comment] 2018-11-16 05:14
Tested and confirmed this issue has been fixed in 0.92.  You can now have upper or lowercase letters in MAC address as long as valid HEX value.

**Closed by patrickbst** 2018-11-16 05:14 UTC
Labels: bug
