### ISSUE TITLE
Compatibiity with Fastchip //e

### ISSUE THREAD

**Issue by a2retro** [burniouf/A2osX#38] opened 2018-07-15 17:08 UTC
When I have my Fastchip //e installed i can only get to the end of stage 2 before it hangs

**Comment by a2retro** [comment] 2018-07-15 17:56
Issue seems intermittent as I was able to boot later. Have issues with CFFA3000 as well. Possibly not related to a2osx.

**Comment by burniouf** [comment] 2018-07-16 08:42
could be timing issue, OR hardware not reset properly.
I had many troubles with RamWorks and Accelerators ....had to add some NOP....  
awaiting more inputs....

**Comment by a2retro** [comment] 2018-07-18 01:56
Yeah how can we debug this hanging at the end of stage2. I have seen it with or without the FastChip //e

Also how do you calculate CPU speed. My fastchip should be clocked at 16Mhz but your detection says 11.38MHz

**Comment by burniouf** [comment] 2018-07-18 07:10
see CPU.Init.6502 in https://github.com/burniouf/A2osX/blob/master/SYS/KERNEL.S.INIT.txt

it uses VBL as a reference clock. Check KCONFIG for proper Timing (50 or 60Hz)
Is this board can set different CPU speed ?
If yes, i'm quite interested in values reported at each possible CPU clock.
it will help tuning this sub more precisely.
Actually i only checked proper CPU speed reported on:
- Overclocked 8Mhz //c+
- Transwarp 3.6 Mhz
- Titan 3.6 Mhz
- Stock 60Hz //e
- Stock //e & //c 50Hz

**Comment by burniouf** [comment] 2018-07-18 07:12
btw, i'm quite sure that I/O access to ram & IO addresses slow down the loop....

**Comment by burniouf** [comment] 2018-09-06 08:26
Could you give a status with this "stage 2 hang" with the latest 0.92 media ?

**Comment by patrickbst** [comment] 2018-12-26 19:43
I would be glad to help you get things set up.  A couple of suggestions to come to mind.

First) When booting, press Control-R for Root/Maintenance mode.  This will startup A2OSX and skip the loading of ETC/INIT which skips some drivers/bins.  You should get a $ prompt (and it should give you messages saying it is booting to ROOT mode).  Does this work?

Second) Try disabling the Transwarp card before booting.

Third) Is the hard(ware) one.  It sounds like there might be a conflict with one of the cards.  The SSC, Uther2, and Disk Controller are known to work.  My guess in terms of suspects (in order) are the Transwarp, IDE, AE Ram and Mockingboard (though I dont think I have ever heard of one in an A2osx system so that could mean never a problem or its the cause <g>).  It would really be a great help to us to identify and known conflicts, sooo...  If you can either pull one at a time..or..pull all these, boot make sure you get past 3 then start putting them back 1 at a time until we find the culprit.

FYI, we have a slack channel (a2osx.slack.com) that we would be happy to have you join where we do real time messaging/discussions/help with a2osx.

**Comment by patrickbst** [comment] 2018-12-27 00:31
A couple of things come to mind.  First is you must have a 65C02, which I believe you have in a Platinum.  Second, you must have an extended 80-col card (in other words you must have 128K of memory).  You did not mention what was in the aux slot, but it needs a 64K or greater card.  The Ram Factor in Slot 7 would not count (it would be useful as a RamDisk) but does not add the bank switching base memory that you get from 128K apple.  Can you confirm your memory?

**Comment by patrickbst** [comment] 2019-03-29 20:42
@hdunsany Are you still using A2osX?  Have you tested any of the lastest builds on your machines?

**Comment by patrickbst** [comment] 2019-03-29 20:42
@a2retro Have not heard from you lately on this issue?  Can we go ahead and close?

**Comment by burniouf** [comment] 2019-10-18 13:29
@a2retro : Fix for Smartport boards like CFFA in .93 BUILD 1648 
please check and close

**Comment by patrickbst** [comment] 2019-11-03 02:46
Summary/Update and closing of this issue.  1) When using any Accelerator, users need to be sure to configure slots slow/fast as appropriate for each card.  DOC has been updated in the HW section of the User Guide.  2) Specifically with the FastChip, RamWorks/RamFactor options may need to be disabled (more testing needed with latest build).  Again DOC updated.  3) There was an issue when the number of SmartPort devices exceeded 4 as was possible with CFFA cards, when more then 1 mass storage emulator was plugged in (CFFA, MicroTurbo, Booti, etc).  This has been addressed. Another issue cropped up with too many devices (>16) which included all these HDS as well as Net cards, SSC, TTY, etc.  THis has been addressed. In addition, a new DEBUG image has been added to the media folder and its use has been documented in the User Guide.

**Closed by patrickbst** 2019-11-03 02:46 UTC
