### ISSUE TITLE
Telnet session to Linux box shows garbage characters and scrolling behaves oddly

### ISSUE THREAD

**Issue by Allenjs5** [burniouf/A2osX#104] opened 2019-04-30 23:36 UTC
Hi team!

I've been playing with A2osX 0.92 on my Platinum IIe with Uthernet II card and was hoping to use it's telnet function to telnet to my Raspberry Pi so I could get onto IRC.  However, once I telnet into the Raspberry Pi, there are some garbage characters showing up in my prompt, which I'm attaching a picture of in Screenshot1.jpg  
![Screenshot1](https://user-images.githubusercontent.com/50157138/56999713-55243b80-6b7e-11e9-8d29-ea91bd2a5baf.jpg)
I push past that and loaded irssi, and it's output is a bit garbled and not fully clearing what's on the screen when it draws for the first time, which I'm showing an example of in Screenshot2.jpg 
![Screenshot2](https://user-images.githubusercontent.com/50157138/56999857-07f49980-6b7f-11e9-8052-cb6008de4740.jpg)

Lastly, there are issues with the scrolling in irssi, where the screen doesn't scroll up, but each new line of texts overwrites itself at the bottom of the screen, which I'm attaching in Screenshot3.jpg although its hard to see exactly what it's doing but the nick list that loads at the beginning when joining a channel never scrolls off the screen.  
![Screenshot3](https://user-images.githubusercontent.com/50157138/56999832-ea273480-6b7e-11e9-8c05-2b4c6fa43a01.jpg)

Admittedly, I'm not super well versed in Linux, so if it's a matter of a setting I need to change on the Pi to get the text and scrolling to format correctly, I apologize in advance.   If there's any more information or examples or screenshots I can provide, just let me know, as I'd really love to be able to use this, it would make A2osX a daily driver for me on my IIe.

Thank you!
-Josh

**Comment by patrickbst** [comment] 2019-05-01 20:01
Josh we have posted a new Floppy for you to try in the Floppies section, it is called STABLE.140.dsk,  It is currently set to boot/run under AW (which uses a UTHERNET not UII), so you will have to edit the ETC/INIT file to change drivers and if you need to use static addresses you will need to rename TCPIP.HOLD to TCPIP.CONF and then edit to fit your network needs.  Can you please try this new build and provide us feedback.  Thanks.  

PS, we have a SLACK channel for real time chat with testers of A2osX, I would be happy to send you an invite if you like, just let me know your email address.

**Comment by Allenjs5** [comment] 2019-05-01 22:19
Hey there, I would love an invite, my email address is Allenjs5@gmail.com

Out of curiosity, should this new image, or any of them, work on a IIGS?  I happened to acquire one yesterday and I only have the one Uthernet II card at the moment which I've put in the IIGS and when I tried to boot this disk you uploaded today I get as far as the device manager loading and I get a white box with RESTART SYSTEM-$01 in it.  Same with the disk I was using on my IIe.   A new copy of A2OSX.BOOT also only gets as far as adding /DEV/S3D2, /DEV/S6D1, /DEV/S6D2 before it just hangs with no error so I'm not sure if I need to change a setting on my IIGS to make these work?

If they're not compatible at all, I can pop the card back in my IIe to test the disk, it just probably won't be until tomorrow that I will have time to do that.

Thanks again!

**Comment by patrickbst** [comment] 2019-05-01 22:34
I sent you the invite to Slack.  Yes A2osX works on a GS, but we have seen some HW conflicts with some cards in some slots.  I believe one issue is putting the U2 in slot 3, which we do in //e's with no problem but that has problems on a GS.  Forgive me I am trying to recall the permutations :).  But bottomline, yes A2osX works on a GS.  So what is your config?  What is in what slots?  How do you have control panel set?  I am about to use that very disk on my own GS (I had not yet) and will give some feedback.

**Comment by Allenjs5** [comment] 2019-05-01 22:48
I originally had the Uthernet II in slot 3 like I did on my IIe, I've now moved it to slot 7.  Control panel has slot 7 set to Your Card, and I'm getting the same errors as I was with it in slot 3.

**Comment by ailin-nemui** [comment] 2019-05-02 12:27
did you try different TERM variables? not clear which ones A2 can support but these are the first things to check about screen scrolling

**Comment by ailin-nemui** [comment] 2019-05-02 14:09
( the programs inside telnet/remote unix might send some non-vt100 codes, and might (or might not) listen to TERM )

**Comment by burniouf** [comment] 2019-05-02 16:03
A2osX TTYs answer "XTERM" to ENQ and TTYPE server commands. probably not asked by rasberry or misunderstood

**Comment by ailin-nemui** [comment] 2019-05-02 17:49
nb answering XTERM is probably incorrect, since xterm supports very many functions

**Comment by burniouf** [comment] 2019-05-02 18:37
has been tested against several telnet servers.....Linux, windows....some BBS....no particular issues...

**Comment by patrickbst** [comment] 2019-05-24 01:23
There has been some updates to the Telnet/VT100 escape sequence handling in A2osx that might impact this issue.  In addition the networking of A2osX has been updated.  Can you please test this issue again on your system.

**Comment by Allenjs5** [comment] 2019-05-25 00:31
![20190525_000608064_iOS](https://user-images.githubusercontent.com/50157138/58362189-66e9bd80-7e62-11e9-97cc-3e87290973b9.jpg)
Hey guys, I just got a chance to try this out, and it doesn't seem to have changed much for me.  I even did an export TERM=vt100 on my raspberrypi once connected, but as the screenshot will show the scrolling in irssi still doesn't work.   Also I still get the duplicated prompt in my first screenshot and the occasional socket error $27 when trying to connect, and also the occasional connection where it jumps straight to the password prompt.

**Comment by burniouf** [comment] 2019-05-25 07:59
this is not a scrolling issue.
i think it is related to vt100 "SETMODE linefeed/newline" currently not supported by A2osX

 `\e[20h` incoming  LF = CR/LF, ENTER key = CR/LF
 `\e[20l` incoming  LF = LF, ENTER key = CR

see https://vt100.net/docs/vt100-ug/chapter3.html
( LNM section )

This should solve both "login:" & "scrolling" problems

**Comment by burniouf** [comment] 2019-05-25 08:06
could someone confirm that with a network trace showing those ESC sequences sent by Raspberry, and reading this link to make i understand the \e[20 stuff properly

**Comment by burniouf** [comment] 2019-05-26 06:38
Implemented in latest BUILD

**Comment by Allenjs5** [comment] 2019-05-26 19:07
Hey there, grabbed the latest BUILD and the login: issue is still occurring, but in positive news, if I export TERM=vt100 and then start irssi, it works great!   Thank you!  I can still provide a network trace for further troubleshooting of the login prompt issue, if you'd like.  Just let me know!

**Comment by Allenjs5** [comment] 2019-05-26 19:26
file:///home/josh/Downloads/Latest%202GS%20to%20PI.pcapng.zip
Here's the latest network trace from my last connection to the Pi, where i got jumped straight down to password.   Once logged in, everything else is great!

**Comment by Allenjs5** [comment] 2019-05-26 19:27
[Latest 2GS to PI.pcapng.zip](https://github.com/burniouf/A2osX/files/3221031/Latest.2GS.to.PI.pcapng.zip)
Here's the latest network trace, I connected in and it dropped me right to password: 
After that though it's working great!

**Comment by burniouf** [comment] 2019-10-19 20:16
Has been corrected in latest RC medias.
Please give a test and close the issue accordingly.

**Comment by patrickbst** [comment] 2019-10-31 17:56
All of the latest builds have fixed the drop to passwd problem.  Reconfirmed issue is fixed in 1694.  As the scrolling and other problems reported in this issue have been fixed and confirmed, closing.

**Closed by patrickbst** 2019-10-31 17:56 UTC
