### ISSUE TITLE
Shell sometimes prints prompt on tail end of previous output

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#14] opened 2016-11-13 05:08 UTC
If I do this:

/A2OSX.BOOT/$ CD etc
/A2OSX.BOOT/ETC$ CAT hostname
a2osx-host/A2OSX.BOOT/ETC/$ 

...because "hostname" doesn't end with a trailing CR, the prompt is printed right after it, confusing the output.

I suggest doing what other Linux shells do. When it's time to print the command prompt, check to see if we are on column 1, and if not, print a CR first.

What I see other shells doing is also printing a little ⏎ symbol before the CR to indicate that the output doesn't have a CR in it.

**Comment by burniouf** [comment] 2016-11-25 08:36
do do that, whe need something like "GetCursorPos" implemented in ANSI support within CONSOLE/SHELL.
i planned to move off ANSI from SHELL & other commands in a separate X.ANSI module, as i need it for the ADT client i'm currently working on. (btw, for ADT client, i drives me to write LIBDISKII.o, and add SmartPort support in the KERNEL.....which lead in the DEVMGR rewrite....etc...etc...)

**Comment by xandark** [comment] 2016-11-27 03:25
oh yes, yes, I am familiar with that kind of refactoring... but it makes it much better because of it

cool to hear about the ADT client!

**Comment by patrickbst** [comment] 2019-03-29 20:18
The original problem being discussed here is somewhat specific to CAT, so couldn't just change CAT to check to see if the last char it printed before exiting was a CR or CR/LF combo or whatever you need to, and if that was not the last char, then print one.

**Comment by patrickbst** [comment] 2019-03-29 21:28
#58 Was a dupe of this one.

I was about to write a whole thing of what the solution should be and actually went back and forth between adding CRs to shell, to Cat, to X  **OR**  not well because you would break piping or other stuff.  Then I stopped and went to Linux and it turns out it behaves just as A2osX does right now.  If you cat a file that does not end in CR, prompt appears at end of that line.  The one thing I did note is that the editors there (in Linux) end all text files with a CR.  We should make sure EDIT for A2osX does the same thing.  If not, open a new EDIT issue to fix.

Closing this issue because behavior is correct.

**Comment by patrickbst** [comment] 2019-03-29 21:31
NOTE in A2osX, if you EDIT a file and just type 3 chars, then save.  then cat this file, it displays with new line (suggesting there is a CR there).  When you LS -L length shows 3.  In Linux, if you do the same thing, you get a file with length of 4.  It counts the CR it added.  So is there a CR in the A2oSX text file?  is length set wrong?  Leaving this open for Remy to answer.

**Comment by patrickbst** [comment] 2019-05-24 01:39
No long an issue.  A newline is always generated now.

**Closed by patrickbst** 2019-05-24 01:39 UTC
Labels: question

**Comment by xandark** [comment] 2019-05-27 22:46
Excellent! I'm still observing this project, and intend to give more time when my life becomes more predictable.
