### ISSUE TITLE
SH: Issue when mutiple PIPEs in command line

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#106] opened 2019-10-18 23:30 UTC
![Screenshot 2019-10-18 16:15:20](https://user-images.githubusercontent.com/5048913/67133934-159cea80-f1c4-11e9-97e7-be35be24ce4c.jpeg)

$ CD /MINIBOOT
$ LS -L | CUT -F 1
PID=13
BIN

We should get many more than the first item.

**Comment by xandark** [comment] 2019-10-18 23:30
This was with RC 1643

**Comment by burniouf** [comment] 2019-10-19 19:39
FIX in 1653

must be checked deeply when piping....etc...

**Comment by patrickbst** [comment] 2019-10-25 01:06
Tested and can confirm that CUT no longer stops after the first line.  However, in testing CUT with PIPE input/output new errors were confirmed.  Note the attached screen shot, where the first example worked fine, but then when piping result of one cut to another, results were wrong and in fact it looks like the output is the result of cutting the help screen output of the cut command itself.
![image](https://user-images.githubusercontent.com/180313/67535769-117c3b80-f6a2-11e9-9926-493ee1ca453b.png)

**Comment by patrickbst** [comment] 2019-10-31 17:27
Tested multiple examples in 1694.  No issues. This issue has been fixed.  Closing.

**Closed by patrickbst** 2019-10-31 17:27 UTC
